# nombre de tu proyecto.
service: erp-serverless

frameworkVersion: "3"

plugins:
  - serverless-offline
# Carga automáticamente variables desde el archivo `.env` en local
# (útil para desarrollo académico).
useDotenv: true

provider:
  # El proveedor de nube que se va a utilizar (en este caso, AWS).
  name: aws
  # lenguaje y versión de tus funciones Lambda.
  runtime: python3.12
  # región de AWS donde se desplegaría.
  region: us-east-1
  # entorno (dev, prod, test).
  stage: dev
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

# Define las funciones Lambda
functions:
  # es el nombre de la función Lambda 
  clientes:
    handler: lambdas/clientes/handler.lambda_handler
    # triggers que hacen que la función se ejecute
    events:
      - http:
          path: /clientes
          method: get
      - http:
          path: /clientes
          method: post

  ventas:
    handler: lambdas/ventas/handler.lambda_handler
    events:
      - http:
          path: /ventas
          method: get
      - http:
          path: /ventas
          method: post

  compras:
    handler: lambdas/compras/handler.lambda_handler
    events:
      - http:
          path: /compras
          method: get
      - http:
          path: /compras
          method: post

  inventario:
    handler: lambdas/inventario/handler.lambda_handler
    events:
      - http:
          path: /inventario
          method: get
      - http:
          path: /inventario
          method: put